
def load_regular_table(fname, ncol=None, sort=None):
    """
    Load table generated by Thermo-Calc

    Parameters
    ----------
    fname : string
        File name
    ncol : integer
        Number of columns in the file/data
    sort : integer, optional
        If a integer is supplied, the data will be sorted based on the
        'sort'-th column; default: None

    Returns
    -------
    tuple of array_like objects containing the thermodynamical data 
    gotten from the file 'fname'.
    """
    data = []
    with open(fname, errors='ignore') as f:
        for line in f:
            try:
                arr = list(map(float, line.split()))
                if len(arr) > 0:
                    if ncol is not None:
                        if len(arr) == ncol:
                            data.append(arr)
                    else:
                        data.append(arr)
            except:
                pass
    data = np.array(data)
    if isinstance(sort, int):
        try:
            ind = np.argsort(data[:, sort])
            data = data[ind, :]
        except:
            print('Invalid value of "sort". Sorting ignored.')
    return data
